# Generated by Django 5.0.7 on 2024-08-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_rental'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='dayEntrance',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='rental',
            name='dayExit',
            field=models.DateField(null=True),
        ),
    ]
